### ISSUE TITLE
CandyArray should support #map

### ISSUE THREAD

**Issue by dominikh** [SFEley/candy#13]
The title basically says it all, CandyArray should support #map, unless I am missing a more obvious/efficient way of doing this:

https://gist.github.com/99e9f4b81a05edbd4740

**Comment by SFEley** [comment]
Argh.  You're completely right, of course.  I've just done the trivial work it needed to make CandyArray enumerable -- sorry for taking so long on it.  It's in release 0.2.10: 28eb0c569d88

**Comment by dominikh** [comment]
Thanks :)
